- hosts: docker-node
  become: true
  tasks:
    - name: Install prereq packages
      package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        update_cache: true

    - name: Install Docker apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        id: 0EBFCD88

    - name: Install Docker apt repo
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts.ansible_lsb.codename }} stable'
        update_cache: true

    - name: Install Docker packages
      package:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']

    - name: Let me docker
      user:
        name: skibler
        groups:
          - docker
        append: true
