version: 2.1
jobs:
  lint:
    docker:
      - image: particlekit/ansible-lint

    steps:
      - checkout
      - run: find . -maxdepth 1 -type f -name '*.yml' ! -name requirements.yml -print0 | xargs -0 -- ansible-lint -x 503
workflows:
  build:
    jobs:
      - lint
